name: Spell Check

permissions:
  pull-requests: write  # Allows creating/updating PR comments
  contents: read       # Allows reading repository contents

on:
  pull_request:
  push:
    branches: [dev, main]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'pull_request'  # Only run on pull requests

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
         

      - name: Install cspell
        run: npm install -g cspell

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }} HEAD | grep -E '\.(php|blade\.php|md|yml|yaml|json|js|jsx|ts|tsx|css|scss|vue)$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run cspell on changed files
        id: spell-check
        run: |
          if [ -z "${{ steps.changed-files.outputs.files }}" ]; then
            echo "No files to check"
            echo "spell_check_result=" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Checking spelling in changed files..."
          cspell --no-progress --config "cspell.json" ${{ steps.changed-files.outputs.files }} > spell_check_output.txt || true
          spell_check_output=$(cat spell_check_output.txt)
          spell_check_output="${spell_check_output//'%'/'%25'}"
          spell_check_output="${spell_check_output//$'\n'/'%0A'}"
          spell_check_output="${spell_check_output//$'\r'/'%0D'}"
          echo "spell_check_result=$spell_check_output" >> $GITHUB_OUTPUT

      - name: Post Spell Check Results
        if: always()
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            **Spell Check Results:**

            ```plaintext
            ${{ steps.spell-check.outputs.spell_check_result }}
            ```
          github-token: ${{ secrets.GH }}
          comment-tag: spell-check-result
          mode: upsert
          create-if-not-exists: true
