name: Spell Check

permissions:
  pull-requests: write  # Allows creating/updating PR comments
  contents: read        # Allows reading repository contents

on:
  pull_request:
  push:
    branches: [dev, main]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'pull_request'  # Only run on pull requests

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install cspell
        run: npm install -g cspell

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }} HEAD | grep -E '\.(php|blade\.php|md|yml|yaml|json|js|jsx|ts|tsx|css|scss|vue)$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run cspell on changed files
        id: spell-check
        run: |
          if [ -z "${{ steps.changed-files.outputs.files }}" ]; then
            echo "No files to check"
            echo "spell_check_result=" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "Checking spelling in changed files..."
          cspell --no-progress --config "cspell.json" ${{ steps.changed-files.outputs.files }} > cspell-output.txt || true
          
          if [ -s cspell-output.txt ]; then
            # Create a properly formatted markdown table
            {
              echo "## 📝 Spell Check Results"
              echo
              echo "| File | Line | Error | Suggested Fix |"
              echo "|------|------|-------|---------------|"
              while IFS= read -r line; do
                file=$(echo "$line" | cut -d: -f1)
                line_number=$(echo "$line" | cut -d: -f2)
                error=$(echo "$line" | cut -d: -f3- | sed 's/^[[:space:]]*//')
                suggestion=$(echo "$error" | grep -oP 'Unknown word \(\K[^)]+')
                
                # Properly escape markdown special characters
                file=$(echo "$file" | sed 's/|/\\|/g')
                error=$(echo "$error" | sed 's/|/\\|/g')
                suggestion=$(echo "$suggestion" | sed 's/|/\\|/g')
                
                echo "| \`$file\` | $line_number | $error | $suggestion |"
              done < cspell-output.txt
            } > results.md
            
            # Properly escape the content for GitHub Actions
            spell_check_result=$(cat results.md)
            spell_check_result="${spell_check_result//'%'/'%25'}"
            spell_check_result="${spell_check_result//$'\n'/'%0A'}"
            spell_check_result="${spell_check_result//$'\r'/'%0D'}"
            echo "spell_check_result<<EOF" >> $GITHUB_OUTPUT
            echo "$spell_check_result" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "spell_check_result=## 🎉 No spelling errors found!" >> $GITHUB_OUTPUT
          fi

      - name: Post Spell Check Results
        if: always()
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.spell-check.outputs.spell_check_result }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-tag: spell-check-result
          mode: upsert
          create-if-not-exists: true
